/* prompt-options-data.jsx — 배경500/분위기100/날씨100 (prompt-data.jsx 이후 로드되어 덮어씀) */
window.BACKGROUNDS = [
  {"value":"ancient forest","label":"고대 숲"},
  {"value":"bamboo grove","label":"대나무 숲"},
  {"value":"pine forest","label":"소나무 숲"},
  {"value":"maple grove","label":"단풍 숲"},
  {"value":"birch woodland","label":"자작나무 숲"},
  {"value":"wildflower meadow","label":"들꽃 들판"},
  {"value":"mountain peak","label":"산 정상"},
  {"value":"rolling hills","label":"구릉 언덕"},
  {"value":"river bank","label":"강가"},
  {"value":"lakeside","label":"호숫가"},
  {"value":"seaside cliff","label":"바닷가 절벽"},
  {"value":"sandy beach","label":"모래 해변"},
  {"value":"coral reef shore","label":"산호초 해안"},
  {"value":"waterfall basin","label":"폭포 아래"},
  {"value":"hot spring","label":"온천"},
  {"value":"desert dunes","label":"사막 모래언덕"},
  {"value":"oasis","label":"오아시스"},
  {"value":"canyon gorge","label":"협곡"},
  {"value":"volcanic plateau","label":"화산 고원"},
  {"value":"glacier valley","label":"빙하 계곡"},
  {"value":"frozen tundra","label":"얼어붙은 툰드라"},
  {"value":"snowfield","label":"설원"},
  {"value":"ice cave","label":"얼음 동굴"},
  {"value":"limestone cave","label":"석회 동굴"},
  {"value":"moss-covered ruins","label":"이끼 낀 폐허"},
  {"value":"stone temple","label":"석조 사원"},
  {"value":"mountain monastery","label":"산사"},
  {"value":"zen rock garden","label":"선 정원"},
  {"value":"lotus pond","label":"연꽃 연못"},
  {"value":"terraced rice fields","label":"계단식 논"},
  {"value":"country road","label":"시골길"},
  {"value":"old farmhouse","label":"오래된 농가"},
  {"value":"barn at dusk","label":"해질녘 헛간"},
  {"value":"vineyard hillside","label":"포도밭 언덕"},
  {"value":"lavender field","label":"라벤더 밭"},
  {"value":"sunflower field","label":"해바라기 밭"},
  {"value":"tea plantation","label":"차밭"},
  {"value":"orchard in bloom","label":"꽃핀 과수원"},
  {"value":"wheat field","label":"밀밭"},
  {"value":"misty marsh","label":"안개 낀 습지"},
  {"value":"mangrove swamp","label":"맹그로브 늪"},
  {"value":"fjord coast","label":"피오르 해안"},
  {"value":"island lagoon","label":"섬 석호"},
  {"value":"lighthouse point","label":"등대곶"},
  {"value":"harbor at dawn","label":"새벽 항구"},
  {"value":"fishing village","label":"어촌"},
  {"value":"old town alley","label":"구시가 골목"},
  {"value":"cobblestone square","label":"자갈 광장"},
  {"value":"cathedral interior","label":"대성당 내부"},
  {"value":"library hall","label":"도서관 홀"},
  {"value":"museum gallery","label":"미술관 전시실"},
  {"value":"artist studio","label":"화가의 작업실"},
  {"value":"wooden cabin","label":"통나무 오두막"},
  {"value":"attic room","label":"다락방"},
  {"value":"candlelit study","label":"촛불 켠 서재"},
  {"value":"empty theater","label":"빈 극장"},
  {"value":"train station platform","label":"기차역 승강장"},
  {"value":"rooftop terrace","label":"옥상 테라스"},
  {"value":"city skyline","label":"도시 스카이라인"},
  {"value":"neon street","label":"네온 거리"},
  {"value":"rainy boulevard","label":"비 내리는 대로"},
  {"value":"bridge over river","label":"강 위 다리"},
  {"value":"park bench path","label":"공원 벤치 길"},
  {"value":"botanical greenhouse","label":"식물 온실"},
  {"value":"courtyard garden","label":"안뜰 정원"},
  {"value":"palace hall","label":"궁전 홀"},
  {"value":"ancient amphitheater","label":"고대 원형극장"},
  {"value":"desert caravan trail","label":"사막 대상로"},
  {"value":"mountain pass","label":"산길 고개"},
  {"value":"cliffside path","label":"절벽 길"},
  {"value":"forest clearing","label":"숲속 빈터"},
  {"value":"hidden waterfall","label":"숨은 폭포"},
  {"value":"star-filled sky","label":"별 가득한 하늘"},
  {"value":"aurora over snow","label":"설원의 오로라"},
  {"value":"milky way desert","label":"은하수 사막"},
  {"value":"sunset horizon","label":"노을 지평선"},
  {"value":"dawn over sea","label":"바다 위 새벽"},
  {"value":"foggy valley","label":"안개 낀 계곡"},
  {"value":"cherry blossom path","label":"벚꽃길"},
  {"value":"autumn park","label":"가을 공원"},
  {"value":"winter lake","label":"겨울 호수"},
  {"value":"spring riverside","label":"봄 강변"},
  {"value":"summer field","label":"여름 들판"},
  {"value":"moonlit garden","label":"달빛 정원"},
  {"value":"abandoned chapel","label":"버려진 예배당"},
  {"value":"ruined castle","label":"폐성"},
  {"value":"ancient library ruins","label":"고대 도서관 폐허"},
  {"value":"floating clouds peak","label":"구름 위 봉우리"},
  {"value":"cloud sea overlook","label":"운해 전망"},
  {"value":"misty bamboo path","label":"안개 낀 대숲길"},
  {"value":"quiet courtyard well","label":"고요한 우물 마당"},
  {"value":"temple staircase","label":"사원 계단"},
  {"value":"pagoda hill","label":"탑이 있는 언덕"},
  {"value":"riverside willow","label":"강가 버드나무"},
  {"value":"reed wetland","label":"갈대 습지"},
  {"value":"salt flat mirror","label":"거울 같은 소금 사막"},
  {"value":"red rock desert","label":"붉은 바위 사막"},
  {"value":"alpine meadow","label":"고산 초원"},
  {"value":"foggy pine ridge","label":"안개 낀 솔숲 능선"},
  {"value":"coastal tide pools","label":"해안 조수 웅덩이"},
  {"value":"driftwood beach","label":"유목 해변"},
  {"value":"sea cave arch","label":"바다 동굴 아치"},
  {"value":"snowy village","label":"눈 덮인 마을"},
  {"value":"frozen waterfall","label":"얼어붙은 폭포"},
  {"value":"northern forest lake","label":"북방 숲 호수"},
  {"value":"desert night camp","label":"사막 야영지"},
  {"value":"cactus valley","label":"선인장 계곡"},
  {"value":"windswept moor","label":"바람 부는 황야"},
  {"value":"highland loch","label":"고지 호수"},
  {"value":"stone bridge stream","label":"돌다리 시내"},
  {"value":"mountain shrine","label":"산정 사당"},
  {"value":"ink-wash mountains","label":"수묵 산수"},
  {"value":"paper lantern street","label":"종이 등 거리"},
  {"value":"festival night market","label":"축제 야시장"},
  {"value":"snow garden pavilion","label":"눈 정원 정자"},
  {"value":"plum blossom courtyard","label":"매화 안뜰"},
  {"value":"pine cliff overlook","label":"솔 절벽 전망"},
  {"value":"river delta sunrise","label":"강 삼각주 일출"},
  {"value":"terrace tea house","label":"테라스 찻집"},
  {"value":"scholar's pavilion","label":"선비의 정자"},
  {"value":"wind chime porch","label":"풍경 달린 툇마루"},
  {"value":"empty road horizon","label":"텅 빈 길 지평선"},
  {"value":"infinite staircase","label":"무한 계단"},
  {"value":"floating islands","label":"떠 있는 섬들"},
  {"value":"mirror lake reflection","label":"거울 호수"},
  {"value":"endless bookshelves","label":"끝없는 책장"},
  {"value":"clockwork chamber","label":"태엽 방"},
  {"value":"starlit observatory","label":"별빛 천문대"},
  {"value":"misty graveyard","label":"안개 낀 묘지"},
  {"value":"candle hall of memory","label":"기억의 촛불 홀"},
  {"value":"abstract void space","label":"추상적 공허 공간"},
  {"value":"geometric dreamscape","label":"기하학 꿈 풍경"},
  {"value":"ancient forest at dawn","label":"새벽의 고대 숲"},
  {"value":"bamboo grove at dawn","label":"새벽의 대나무 숲"},
  {"value":"pine forest at dawn","label":"새벽의 소나무 숲"},
  {"value":"maple grove at dawn","label":"새벽의 단풍 숲"},
  {"value":"birch woodland at dawn","label":"새벽의 자작나무 숲"},
  {"value":"wildflower meadow at dawn","label":"새벽의 들꽃 들판"},
  {"value":"mountain peak at dawn","label":"새벽의 산 정상"},
  {"value":"rolling hills at dawn","label":"새벽의 구릉 언덕"},
  {"value":"river bank at dawn","label":"새벽의 강가"},
  {"value":"lakeside at dawn","label":"새벽의 호숫가"},
  {"value":"seaside cliff at dawn","label":"새벽의 바닷가 절벽"},
  {"value":"sandy beach at dawn","label":"새벽의 모래 해변"},
  {"value":"coral reef shore at dawn","label":"새벽의 산호초 해안"},
  {"value":"waterfall basin at dawn","label":"새벽의 폭포 아래"},
  {"value":"hot spring at dawn","label":"새벽의 온천"},
  {"value":"desert dunes at dawn","label":"새벽의 사막 모래언덕"},
  {"value":"oasis at dawn","label":"새벽의 오아시스"},
  {"value":"canyon gorge at dawn","label":"새벽의 협곡"},
  {"value":"volcanic plateau at dawn","label":"새벽의 화산 고원"},
  {"value":"glacier valley at dawn","label":"새벽의 빙하 계곡"},
  {"value":"frozen tundra at dawn","label":"새벽의 얼어붙은 툰드라"},
  {"value":"snowfield at dawn","label":"새벽의 설원"},
  {"value":"ice cave at dawn","label":"새벽의 얼음 동굴"},
  {"value":"limestone cave at dawn","label":"새벽의 석회 동굴"},
  {"value":"moss-covered ruins at dawn","label":"새벽의 이끼 낀 폐허"},
  {"value":"stone temple at dawn","label":"새벽의 석조 사원"},
  {"value":"mountain monastery at dawn","label":"새벽의 산사"},
  {"value":"zen rock garden at dawn","label":"새벽의 선 정원"},
  {"value":"lotus pond at dawn","label":"새벽의 연꽃 연못"},
  {"value":"terraced rice fields at dawn","label":"새벽의 계단식 논"},
  {"value":"country road at dawn","label":"새벽의 시골길"},
  {"value":"old farmhouse at dawn","label":"새벽의 오래된 농가"},
  {"value":"barn at dusk at dawn","label":"새벽의 해질녘 헛간"},
  {"value":"vineyard hillside at dawn","label":"새벽의 포도밭 언덕"},
  {"value":"lavender field at dawn","label":"새벽의 라벤더 밭"},
  {"value":"sunflower field at dawn","label":"새벽의 해바라기 밭"},
  {"value":"tea plantation at dawn","label":"새벽의 차밭"},
  {"value":"orchard in bloom at dawn","label":"새벽의 꽃핀 과수원"},
  {"value":"wheat field at dawn","label":"새벽의 밀밭"},
  {"value":"misty marsh at dawn","label":"새벽의 안개 낀 습지"},
  {"value":"mangrove swamp at dawn","label":"새벽의 맹그로브 늪"},
  {"value":"fjord coast at dawn","label":"새벽의 피오르 해안"},
  {"value":"island lagoon at dawn","label":"새벽의 섬 석호"},
  {"value":"lighthouse point at dawn","label":"새벽의 등대곶"},
  {"value":"harbor at dawn at dawn","label":"새벽의 새벽 항구"},
  {"value":"fishing village at dawn","label":"새벽의 어촌"},
  {"value":"old town alley at dawn","label":"새벽의 구시가 골목"},
  {"value":"cobblestone square at dawn","label":"새벽의 자갈 광장"},
  {"value":"cathedral interior at dawn","label":"새벽의 대성당 내부"},
  {"value":"library hall at dawn","label":"새벽의 도서관 홀"},
  {"value":"museum gallery at dawn","label":"새벽의 미술관 전시실"},
  {"value":"artist studio at dawn","label":"새벽의 화가의 작업실"},
  {"value":"wooden cabin at dawn","label":"새벽의 통나무 오두막"},
  {"value":"attic room at dawn","label":"새벽의 다락방"},
  {"value":"candlelit study at dawn","label":"새벽의 촛불 켠 서재"},
  {"value":"empty theater at dawn","label":"새벽의 빈 극장"},
  {"value":"train station platform at dawn","label":"새벽의 기차역 승강장"},
  {"value":"rooftop terrace at dawn","label":"새벽의 옥상 테라스"},
  {"value":"city skyline at dawn","label":"새벽의 도시 스카이라인"},
  {"value":"neon street at dawn","label":"새벽의 네온 거리"},
  {"value":"rainy boulevard at dawn","label":"새벽의 비 내리는 대로"},
  {"value":"bridge over river at dawn","label":"새벽의 강 위 다리"},
  {"value":"park bench path at dawn","label":"새벽의 공원 벤치 길"},
  {"value":"botanical greenhouse at dawn","label":"새벽의 식물 온실"},
  {"value":"courtyard garden at dawn","label":"새벽의 안뜰 정원"},
  {"value":"palace hall at dawn","label":"새벽의 궁전 홀"},
  {"value":"ancient amphitheater at dawn","label":"새벽의 고대 원형극장"},
  {"value":"desert caravan trail at dawn","label":"새벽의 사막 대상로"},
  {"value":"mountain pass at dawn","label":"새벽의 산길 고개"},
  {"value":"cliffside path at dawn","label":"새벽의 절벽 길"},
  {"value":"forest clearing at dawn","label":"새벽의 숲속 빈터"},
  {"value":"hidden waterfall at dawn","label":"새벽의 숨은 폭포"},
  {"value":"star-filled sky at dawn","label":"새벽의 별 가득한 하늘"},
  {"value":"aurora over snow at dawn","label":"새벽의 설원의 오로라"},
  {"value":"milky way desert at dawn","label":"새벽의 은하수 사막"},
  {"value":"sunset horizon at dawn","label":"새벽의 노을 지평선"},
  {"value":"dawn over sea at dawn","label":"새벽의 바다 위 새벽"},
  {"value":"foggy valley at dawn","label":"새벽의 안개 낀 계곡"},
  {"value":"cherry blossom path at dawn","label":"새벽의 벚꽃길"},
  {"value":"autumn park at dawn","label":"새벽의 가을 공원"},
  {"value":"winter lake at dawn","label":"새벽의 겨울 호수"},
  {"value":"spring riverside at dawn","label":"새벽의 봄 강변"},
  {"value":"summer field at dawn","label":"새벽의 여름 들판"},
  {"value":"moonlit garden at dawn","label":"새벽의 달빛 정원"},
  {"value":"abandoned chapel at dawn","label":"새벽의 버려진 예배당"},
  {"value":"ruined castle at dawn","label":"새벽의 폐성"},
  {"value":"ancient library ruins at dawn","label":"새벽의 고대 도서관 폐허"},
  {"value":"floating clouds peak at dawn","label":"새벽의 구름 위 봉우리"},
  {"value":"cloud sea overlook at dawn","label":"새벽의 운해 전망"},
  {"value":"misty bamboo path at dawn","label":"새벽의 안개 낀 대숲길"},
  {"value":"quiet courtyard well at dawn","label":"새벽의 고요한 우물 마당"},
  {"value":"temple staircase at dawn","label":"새벽의 사원 계단"},
  {"value":"pagoda hill at dawn","label":"새벽의 탑이 있는 언덕"},
  {"value":"riverside willow at dawn","label":"새벽의 강가 버드나무"},
  {"value":"reed wetland at dawn","label":"새벽의 갈대 습지"},
  {"value":"salt flat mirror at dawn","label":"새벽의 거울 같은 소금 사막"},
  {"value":"red rock desert at dawn","label":"새벽의 붉은 바위 사막"},
  {"value":"alpine meadow at dawn","label":"새벽의 고산 초원"},
  {"value":"foggy pine ridge at dawn","label":"새벽의 안개 낀 솔숲 능선"},
  {"value":"coastal tide pools at dawn","label":"새벽의 해안 조수 웅덩이"},
  {"value":"driftwood beach at dawn","label":"새벽의 유목 해변"},
  {"value":"sea cave arch at dawn","label":"새벽의 바다 동굴 아치"},
  {"value":"snowy village at dawn","label":"새벽의 눈 덮인 마을"},
  {"value":"frozen waterfall at dawn","label":"새벽의 얼어붙은 폭포"},
  {"value":"northern forest lake at dawn","label":"새벽의 북방 숲 호수"},
  {"value":"desert night camp at dawn","label":"새벽의 사막 야영지"},
  {"value":"cactus valley at dawn","label":"새벽의 선인장 계곡"},
  {"value":"windswept moor at dawn","label":"새벽의 바람 부는 황야"},
  {"value":"highland loch at dawn","label":"새벽의 고지 호수"},
  {"value":"stone bridge stream at dawn","label":"새벽의 돌다리 시내"},
  {"value":"mountain shrine at dawn","label":"새벽의 산정 사당"},
  {"value":"ink-wash mountains at dawn","label":"새벽의 수묵 산수"},
  {"value":"paper lantern street at dawn","label":"새벽의 종이 등 거리"},
  {"value":"festival night market at dawn","label":"새벽의 축제 야시장"},
  {"value":"snow garden pavilion at dawn","label":"새벽의 눈 정원 정자"},
  {"value":"plum blossom courtyard at dawn","label":"새벽의 매화 안뜰"},
  {"value":"pine cliff overlook at dawn","label":"새벽의 솔 절벽 전망"},
  {"value":"river delta sunrise at dawn","label":"새벽의 강 삼각주 일출"},
  {"value":"terrace tea house at dawn","label":"새벽의 테라스 찻집"},
  {"value":"scholar's pavilion at dawn","label":"새벽의 선비의 정자"},
  {"value":"wind chime porch at dawn","label":"새벽의 풍경 달린 툇마루"},
  {"value":"empty road horizon at dawn","label":"새벽의 텅 빈 길 지평선"},
  {"value":"infinite staircase at dawn","label":"새벽의 무한 계단"},
  {"value":"floating islands at dawn","label":"새벽의 떠 있는 섬들"},
  {"value":"mirror lake reflection at dawn","label":"새벽의 거울 호수"},
  {"value":"endless bookshelves at dawn","label":"새벽의 끝없는 책장"},
  {"value":"clockwork chamber at dawn","label":"새벽의 태엽 방"},
  {"value":"starlit observatory at dawn","label":"새벽의 별빛 천문대"},
  {"value":"misty graveyard at dawn","label":"새벽의 안개 낀 묘지"},
  {"value":"candle hall of memory at dawn","label":"새벽의 기억의 촛불 홀"},
  {"value":"abstract void space at dawn","label":"새벽의 추상적 공허 공간"},
  {"value":"geometric dreamscape at dawn","label":"새벽의 기하학 꿈 풍경"},
  {"value":"ancient forest at golden hour","label":"황금빛 시간의 고대 숲"},
  {"value":"bamboo grove at golden hour","label":"황금빛 시간의 대나무 숲"},
  {"value":"pine forest at golden hour","label":"황금빛 시간의 소나무 숲"},
  {"value":"maple grove at golden hour","label":"황금빛 시간의 단풍 숲"},
  {"value":"birch woodland at golden hour","label":"황금빛 시간의 자작나무 숲"},
  {"value":"wildflower meadow at golden hour","label":"황금빛 시간의 들꽃 들판"},
  {"value":"mountain peak at golden hour","label":"황금빛 시간의 산 정상"},
  {"value":"rolling hills at golden hour","label":"황금빛 시간의 구릉 언덕"},
  {"value":"river bank at golden hour","label":"황금빛 시간의 강가"},
  {"value":"lakeside at golden hour","label":"황금빛 시간의 호숫가"},
  {"value":"seaside cliff at golden hour","label":"황금빛 시간의 바닷가 절벽"},
  {"value":"sandy beach at golden hour","label":"황금빛 시간의 모래 해변"},
  {"value":"coral reef shore at golden hour","label":"황금빛 시간의 산호초 해안"},
  {"value":"waterfall basin at golden hour","label":"황금빛 시간의 폭포 아래"},
  {"value":"hot spring at golden hour","label":"황금빛 시간의 온천"},
  {"value":"desert dunes at golden hour","label":"황금빛 시간의 사막 모래언덕"},
  {"value":"oasis at golden hour","label":"황금빛 시간의 오아시스"},
  {"value":"canyon gorge at golden hour","label":"황금빛 시간의 협곡"},
  {"value":"volcanic plateau at golden hour","label":"황금빛 시간의 화산 고원"},
  {"value":"glacier valley at golden hour","label":"황금빛 시간의 빙하 계곡"},
  {"value":"frozen tundra at golden hour","label":"황금빛 시간의 얼어붙은 툰드라"},
  {"value":"snowfield at golden hour","label":"황금빛 시간의 설원"},
  {"value":"ice cave at golden hour","label":"황금빛 시간의 얼음 동굴"},
  {"value":"limestone cave at golden hour","label":"황금빛 시간의 석회 동굴"},
  {"value":"moss-covered ruins at golden hour","label":"황금빛 시간의 이끼 낀 폐허"},
  {"value":"stone temple at golden hour","label":"황금빛 시간의 석조 사원"},
  {"value":"mountain monastery at golden hour","label":"황금빛 시간의 산사"},
  {"value":"zen rock garden at golden hour","label":"황금빛 시간의 선 정원"},
  {"value":"lotus pond at golden hour","label":"황금빛 시간의 연꽃 연못"},
  {"value":"terraced rice fields at golden hour","label":"황금빛 시간의 계단식 논"},
  {"value":"country road at golden hour","label":"황금빛 시간의 시골길"},
  {"value":"old farmhouse at golden hour","label":"황금빛 시간의 오래된 농가"},
  {"value":"barn at dusk at golden hour","label":"황금빛 시간의 해질녘 헛간"},
  {"value":"vineyard hillside at golden hour","label":"황금빛 시간의 포도밭 언덕"},
  {"value":"lavender field at golden hour","label":"황금빛 시간의 라벤더 밭"},
  {"value":"sunflower field at golden hour","label":"황금빛 시간의 해바라기 밭"},
  {"value":"tea plantation at golden hour","label":"황금빛 시간의 차밭"},
  {"value":"orchard in bloom at golden hour","label":"황금빛 시간의 꽃핀 과수원"},
  {"value":"wheat field at golden hour","label":"황금빛 시간의 밀밭"},
  {"value":"misty marsh at golden hour","label":"황금빛 시간의 안개 낀 습지"},
  {"value":"mangrove swamp at golden hour","label":"황금빛 시간의 맹그로브 늪"},
  {"value":"fjord coast at golden hour","label":"황금빛 시간의 피오르 해안"},
  {"value":"island lagoon at golden hour","label":"황금빛 시간의 섬 석호"},
  {"value":"lighthouse point at golden hour","label":"황금빛 시간의 등대곶"},
  {"value":"harbor at dawn at golden hour","label":"황금빛 시간의 새벽 항구"},
  {"value":"fishing village at golden hour","label":"황금빛 시간의 어촌"},
  {"value":"old town alley at golden hour","label":"황금빛 시간의 구시가 골목"},
  {"value":"cobblestone square at golden hour","label":"황금빛 시간의 자갈 광장"},
  {"value":"cathedral interior at golden hour","label":"황금빛 시간의 대성당 내부"},
  {"value":"library hall at golden hour","label":"황금빛 시간의 도서관 홀"},
  {"value":"museum gallery at golden hour","label":"황금빛 시간의 미술관 전시실"},
  {"value":"artist studio at golden hour","label":"황금빛 시간의 화가의 작업실"},
  {"value":"wooden cabin at golden hour","label":"황금빛 시간의 통나무 오두막"},
  {"value":"attic room at golden hour","label":"황금빛 시간의 다락방"},
  {"value":"candlelit study at golden hour","label":"황금빛 시간의 촛불 켠 서재"},
  {"value":"empty theater at golden hour","label":"황금빛 시간의 빈 극장"},
  {"value":"train station platform at golden hour","label":"황금빛 시간의 기차역 승강장"},
  {"value":"rooftop terrace at golden hour","label":"황금빛 시간의 옥상 테라스"},
  {"value":"city skyline at golden hour","label":"황금빛 시간의 도시 스카이라인"},
  {"value":"neon street at golden hour","label":"황금빛 시간의 네온 거리"},
  {"value":"rainy boulevard at golden hour","label":"황금빛 시간의 비 내리는 대로"},
  {"value":"bridge over river at golden hour","label":"황금빛 시간의 강 위 다리"},
  {"value":"park bench path at golden hour","label":"황금빛 시간의 공원 벤치 길"},
  {"value":"botanical greenhouse at golden hour","label":"황금빛 시간의 식물 온실"},
  {"value":"courtyard garden at golden hour","label":"황금빛 시간의 안뜰 정원"},
  {"value":"palace hall at golden hour","label":"황금빛 시간의 궁전 홀"},
  {"value":"ancient amphitheater at golden hour","label":"황금빛 시간의 고대 원형극장"},
  {"value":"desert caravan trail at golden hour","label":"황금빛 시간의 사막 대상로"},
  {"value":"mountain pass at golden hour","label":"황금빛 시간의 산길 고개"},
  {"value":"cliffside path at golden hour","label":"황금빛 시간의 절벽 길"},
  {"value":"forest clearing at golden hour","label":"황금빛 시간의 숲속 빈터"},
  {"value":"hidden waterfall at golden hour","label":"황금빛 시간의 숨은 폭포"},
  {"value":"star-filled sky at golden hour","label":"황금빛 시간의 별 가득한 하늘"},
  {"value":"aurora over snow at golden hour","label":"황금빛 시간의 설원의 오로라"},
  {"value":"milky way desert at golden hour","label":"황금빛 시간의 은하수 사막"},
  {"value":"sunset horizon at golden hour","label":"황금빛 시간의 노을 지평선"},
  {"value":"dawn over sea at golden hour","label":"황금빛 시간의 바다 위 새벽"},
  {"value":"foggy valley at golden hour","label":"황금빛 시간의 안개 낀 계곡"},
  {"value":"cherry blossom path at golden hour","label":"황금빛 시간의 벚꽃길"},
  {"value":"autumn park at golden hour","label":"황금빛 시간의 가을 공원"},
  {"value":"winter lake at golden hour","label":"황금빛 시간의 겨울 호수"},
  {"value":"spring riverside at golden hour","label":"황금빛 시간의 봄 강변"},
  {"value":"summer field at golden hour","label":"황금빛 시간의 여름 들판"},
  {"value":"moonlit garden at golden hour","label":"황금빛 시간의 달빛 정원"},
  {"value":"abandoned chapel at golden hour","label":"황금빛 시간의 버려진 예배당"},
  {"value":"ruined castle at golden hour","label":"황금빛 시간의 폐성"},
  {"value":"ancient library ruins at golden hour","label":"황금빛 시간의 고대 도서관 폐허"},
  {"value":"floating clouds peak at golden hour","label":"황금빛 시간의 구름 위 봉우리"},
  {"value":"cloud sea overlook at golden hour","label":"황금빛 시간의 운해 전망"},
  {"value":"misty bamboo path at golden hour","label":"황금빛 시간의 안개 낀 대숲길"},
  {"value":"quiet courtyard well at golden hour","label":"황금빛 시간의 고요한 우물 마당"},
  {"value":"temple staircase at golden hour","label":"황금빛 시간의 사원 계단"},
  {"value":"pagoda hill at golden hour","label":"황금빛 시간의 탑이 있는 언덕"},
  {"value":"riverside willow at golden hour","label":"황금빛 시간의 강가 버드나무"},
  {"value":"reed wetland at golden hour","label":"황금빛 시간의 갈대 습지"},
  {"value":"salt flat mirror at golden hour","label":"황금빛 시간의 거울 같은 소금 사막"},
  {"value":"red rock desert at golden hour","label":"황금빛 시간의 붉은 바위 사막"},
  {"value":"alpine meadow at golden hour","label":"황금빛 시간의 고산 초원"},
  {"value":"foggy pine ridge at golden hour","label":"황금빛 시간의 안개 낀 솔숲 능선"},
  {"value":"coastal tide pools at golden hour","label":"황금빛 시간의 해안 조수 웅덩이"},
  {"value":"driftwood beach at golden hour","label":"황금빛 시간의 유목 해변"},
  {"value":"sea cave arch at golden hour","label":"황금빛 시간의 바다 동굴 아치"},
  {"value":"snowy village at golden hour","label":"황금빛 시간의 눈 덮인 마을"},
  {"value":"frozen waterfall at golden hour","label":"황금빛 시간의 얼어붙은 폭포"},
  {"value":"northern forest lake at golden hour","label":"황금빛 시간의 북방 숲 호수"},
  {"value":"desert night camp at golden hour","label":"황금빛 시간의 사막 야영지"},
  {"value":"cactus valley at golden hour","label":"황금빛 시간의 선인장 계곡"},
  {"value":"windswept moor at golden hour","label":"황금빛 시간의 바람 부는 황야"},
  {"value":"highland loch at golden hour","label":"황금빛 시간의 고지 호수"},
  {"value":"stone bridge stream at golden hour","label":"황금빛 시간의 돌다리 시내"},
  {"value":"mountain shrine at golden hour","label":"황금빛 시간의 산정 사당"},
  {"value":"ink-wash mountains at golden hour","label":"황금빛 시간의 수묵 산수"},
  {"value":"paper lantern street at golden hour","label":"황금빛 시간의 종이 등 거리"},
  {"value":"festival night market at golden hour","label":"황금빛 시간의 축제 야시장"},
  {"value":"snow garden pavilion at golden hour","label":"황금빛 시간의 눈 정원 정자"},
  {"value":"plum blossom courtyard at golden hour","label":"황금빛 시간의 매화 안뜰"},
  {"value":"pine cliff overlook at golden hour","label":"황금빛 시간의 솔 절벽 전망"},
  {"value":"river delta sunrise at golden hour","label":"황금빛 시간의 강 삼각주 일출"},
  {"value":"terrace tea house at golden hour","label":"황금빛 시간의 테라스 찻집"},
  {"value":"scholar's pavilion at golden hour","label":"황금빛 시간의 선비의 정자"},
  {"value":"wind chime porch at golden hour","label":"황금빛 시간의 풍경 달린 툇마루"},
  {"value":"empty road horizon at golden hour","label":"황금빛 시간의 텅 빈 길 지평선"},
  {"value":"infinite staircase at golden hour","label":"황금빛 시간의 무한 계단"},
  {"value":"floating islands at golden hour","label":"황금빛 시간의 떠 있는 섬들"},
  {"value":"mirror lake reflection at golden hour","label":"황금빛 시간의 거울 호수"},
  {"value":"endless bookshelves at golden hour","label":"황금빛 시간의 끝없는 책장"},
  {"value":"clockwork chamber at golden hour","label":"황금빛 시간의 태엽 방"},
  {"value":"starlit observatory at golden hour","label":"황금빛 시간의 별빛 천문대"},
  {"value":"misty graveyard at golden hour","label":"황금빛 시간의 안개 낀 묘지"},
  {"value":"candle hall of memory at golden hour","label":"황금빛 시간의 기억의 촛불 홀"},
  {"value":"abstract void space at golden hour","label":"황금빛 시간의 추상적 공허 공간"},
  {"value":"geometric dreamscape at golden hour","label":"황금빛 시간의 기하학 꿈 풍경"},
  {"value":"ancient forest under moonlight","label":"달빛 아래 고대 숲"},
  {"value":"bamboo grove under moonlight","label":"달빛 아래 대나무 숲"},
  {"value":"pine forest under moonlight","label":"달빛 아래 소나무 숲"},
  {"value":"maple grove under moonlight","label":"달빛 아래 단풍 숲"},
  {"value":"birch woodland under moonlight","label":"달빛 아래 자작나무 숲"},
  {"value":"wildflower meadow under moonlight","label":"달빛 아래 들꽃 들판"},
  {"value":"mountain peak under moonlight","label":"달빛 아래 산 정상"},
  {"value":"rolling hills under moonlight","label":"달빛 아래 구릉 언덕"},
  {"value":"river bank under moonlight","label":"달빛 아래 강가"},
  {"value":"lakeside under moonlight","label":"달빛 아래 호숫가"},
  {"value":"seaside cliff under moonlight","label":"달빛 아래 바닷가 절벽"},
  {"value":"sandy beach under moonlight","label":"달빛 아래 모래 해변"},
  {"value":"coral reef shore under moonlight","label":"달빛 아래 산호초 해안"},
  {"value":"waterfall basin under moonlight","label":"달빛 아래 폭포 아래"},
  {"value":"hot spring under moonlight","label":"달빛 아래 온천"},
  {"value":"desert dunes under moonlight","label":"달빛 아래 사막 모래언덕"},
  {"value":"oasis under moonlight","label":"달빛 아래 오아시스"},
  {"value":"canyon gorge under moonlight","label":"달빛 아래 협곡"},
  {"value":"volcanic plateau under moonlight","label":"달빛 아래 화산 고원"},
  {"value":"glacier valley under moonlight","label":"달빛 아래 빙하 계곡"},
  {"value":"frozen tundra under moonlight","label":"달빛 아래 얼어붙은 툰드라"},
  {"value":"snowfield under moonlight","label":"달빛 아래 설원"},
  {"value":"ice cave under moonlight","label":"달빛 아래 얼음 동굴"},
  {"value":"limestone cave under moonlight","label":"달빛 아래 석회 동굴"},
  {"value":"moss-covered ruins under moonlight","label":"달빛 아래 이끼 낀 폐허"},
  {"value":"stone temple under moonlight","label":"달빛 아래 석조 사원"},
  {"value":"mountain monastery under moonlight","label":"달빛 아래 산사"},
  {"value":"zen rock garden under moonlight","label":"달빛 아래 선 정원"},
  {"value":"lotus pond under moonlight","label":"달빛 아래 연꽃 연못"},
  {"value":"terraced rice fields under moonlight","label":"달빛 아래 계단식 논"},
  {"value":"country road under moonlight","label":"달빛 아래 시골길"},
  {"value":"old farmhouse under moonlight","label":"달빛 아래 오래된 농가"},
  {"value":"barn at dusk under moonlight","label":"달빛 아래 해질녘 헛간"},
  {"value":"vineyard hillside under moonlight","label":"달빛 아래 포도밭 언덕"},
  {"value":"lavender field under moonlight","label":"달빛 아래 라벤더 밭"},
  {"value":"sunflower field under moonlight","label":"달빛 아래 해바라기 밭"},
  {"value":"tea plantation under moonlight","label":"달빛 아래 차밭"},
  {"value":"orchard in bloom under moonlight","label":"달빛 아래 꽃핀 과수원"},
  {"value":"wheat field under moonlight","label":"달빛 아래 밀밭"},
  {"value":"misty marsh under moonlight","label":"달빛 아래 안개 낀 습지"},
  {"value":"mangrove swamp under moonlight","label":"달빛 아래 맹그로브 늪"},
  {"value":"fjord coast under moonlight","label":"달빛 아래 피오르 해안"},
  {"value":"island lagoon under moonlight","label":"달빛 아래 섬 석호"},
  {"value":"lighthouse point under moonlight","label":"달빛 아래 등대곶"},
  {"value":"harbor at dawn under moonlight","label":"달빛 아래 새벽 항구"},
  {"value":"fishing village under moonlight","label":"달빛 아래 어촌"},
  {"value":"old town alley under moonlight","label":"달빛 아래 구시가 골목"},
  {"value":"cobblestone square under moonlight","label":"달빛 아래 자갈 광장"},
  {"value":"cathedral interior under moonlight","label":"달빛 아래 대성당 내부"},
  {"value":"library hall under moonlight","label":"달빛 아래 도서관 홀"},
  {"value":"museum gallery under moonlight","label":"달빛 아래 미술관 전시실"},
  {"value":"artist studio under moonlight","label":"달빛 아래 화가의 작업실"},
  {"value":"wooden cabin under moonlight","label":"달빛 아래 통나무 오두막"},
  {"value":"attic room under moonlight","label":"달빛 아래 다락방"},
  {"value":"candlelit study under moonlight","label":"달빛 아래 촛불 켠 서재"},
  {"value":"empty theater under moonlight","label":"달빛 아래 빈 극장"},
  {"value":"train station platform under moonlight","label":"달빛 아래 기차역 승강장"},
  {"value":"rooftop terrace under moonlight","label":"달빛 아래 옥상 테라스"},
  {"value":"city skyline under moonlight","label":"달빛 아래 도시 스카이라인"},
  {"value":"neon street under moonlight","label":"달빛 아래 네온 거리"},
  {"value":"rainy boulevard under moonlight","label":"달빛 아래 비 내리는 대로"},
  {"value":"bridge over river under moonlight","label":"달빛 아래 강 위 다리"},
  {"value":"park bench path under moonlight","label":"달빛 아래 공원 벤치 길"},
  {"value":"botanical greenhouse under moonlight","label":"달빛 아래 식물 온실"},
  {"value":"courtyard garden under moonlight","label":"달빛 아래 안뜰 정원"},
  {"value":"palace hall under moonlight","label":"달빛 아래 궁전 홀"},
  {"value":"ancient amphitheater under moonlight","label":"달빛 아래 고대 원형극장"},
  {"value":"desert caravan trail under moonlight","label":"달빛 아래 사막 대상로"},
  {"value":"mountain pass under moonlight","label":"달빛 아래 산길 고개"},
  {"value":"cliffside path under moonlight","label":"달빛 아래 절벽 길"},
  {"value":"forest clearing under moonlight","label":"달빛 아래 숲속 빈터"},
  {"value":"hidden waterfall under moonlight","label":"달빛 아래 숨은 폭포"},
  {"value":"star-filled sky under moonlight","label":"달빛 아래 별 가득한 하늘"},
  {"value":"aurora over snow under moonlight","label":"달빛 아래 설원의 오로라"},
  {"value":"milky way desert under moonlight","label":"달빛 아래 은하수 사막"},
  {"value":"sunset horizon under moonlight","label":"달빛 아래 노을 지평선"},
  {"value":"dawn over sea under moonlight","label":"달빛 아래 바다 위 새벽"},
  {"value":"foggy valley under moonlight","label":"달빛 아래 안개 낀 계곡"},
  {"value":"cherry blossom path under moonlight","label":"달빛 아래 벚꽃길"},
  {"value":"autumn park under moonlight","label":"달빛 아래 가을 공원"},
  {"value":"winter lake under moonlight","label":"달빛 아래 겨울 호수"},
  {"value":"spring riverside under moonlight","label":"달빛 아래 봄 강변"},
  {"value":"summer field under moonlight","label":"달빛 아래 여름 들판"},
  {"value":"moonlit garden under moonlight","label":"달빛 아래 달빛 정원"},
  {"value":"abandoned chapel under moonlight","label":"달빛 아래 버려진 예배당"},
  {"value":"ruined castle under moonlight","label":"달빛 아래 폐성"},
  {"value":"ancient library ruins under moonlight","label":"달빛 아래 고대 도서관 폐허"},
  {"value":"floating clouds peak under moonlight","label":"달빛 아래 구름 위 봉우리"},
  {"value":"cloud sea overlook under moonlight","label":"달빛 아래 운해 전망"},
  {"value":"misty bamboo path under moonlight","label":"달빛 아래 안개 낀 대숲길"},
  {"value":"quiet courtyard well under moonlight","label":"달빛 아래 고요한 우물 마당"},
  {"value":"temple staircase under moonlight","label":"달빛 아래 사원 계단"},
  {"value":"pagoda hill under moonlight","label":"달빛 아래 탑이 있는 언덕"},
  {"value":"riverside willow under moonlight","label":"달빛 아래 강가 버드나무"},
  {"value":"reed wetland under moonlight","label":"달빛 아래 갈대 습지"},
  {"value":"salt flat mirror under moonlight","label":"달빛 아래 거울 같은 소금 사막"},
  {"value":"red rock desert under moonlight","label":"달빛 아래 붉은 바위 사막"},
  {"value":"alpine meadow under moonlight","label":"달빛 아래 고산 초원"},
  {"value":"foggy pine ridge under moonlight","label":"달빛 아래 안개 낀 솔숲 능선"},
  {"value":"coastal tide pools under moonlight","label":"달빛 아래 해안 조수 웅덩이"},
  {"value":"driftwood beach under moonlight","label":"달빛 아래 유목 해변"},
  {"value":"sea cave arch under moonlight","label":"달빛 아래 바다 동굴 아치"},
  {"value":"snowy village under moonlight","label":"달빛 아래 눈 덮인 마을"},
  {"value":"frozen waterfall under moonlight","label":"달빛 아래 얼어붙은 폭포"}
];
window.MOODS = [
  "고요한",
  "사색적인",
  "쓸쓸한",
  "따뜻한",
  "장엄한",
  "숭고한",
  "애틋한",
  "평온한",
  "엄숙한",
  "희망찬",
  "비장한",
  "몽환적인",
  "서정적인",
  "고독한",
  "경건한",
  "담담한",
  "아련한",
  "결연한",
  "겸허한",
  "초연한",
  "잔잔한",
  "서글픈",
  "청량한",
  "묵직한",
  "온화한",
  "아늑한",
  "처연한",
  "담대한",
  "유연한",
  "느긋한",
  "긴장된",
  "불안한",
  "아릿한",
  "뭉클한",
  "벅찬",
  "담백한",
  "고상한",
  "청초한",
  "순수한",
  "담연한",
  "비감한",
  "적막한",
  "유현한",
  "호젓한",
  "산뜻한",
  "의연한",
  "온유한",
  "담대무쌍한",
  "고즈넉한",
  "애잔한",
  "환희에 찬",
  "비통한",
  "평화로운",
  "명상적인",
  "정갈한",
  "청명한",
  "쓸쓸하면서 따뜻한",
  "외롭지만 단단한",
  "담담히 슬픈",
  "고요히 벅찬",
  "성스러운",
  "경외로운",
  "아득한",
  "그윽한",
  "담박한",
  "정적인",
  "역동적인",
  "고요히 결연한",
  "잔잔히 희망찬",
  "쓸쓸히 아름다운",
  "사무치는",
  "애절한",
  "담대히 평온한",
  "숙연한",
  "호연한",
  "청신한",
  "유장한",
  "담연히 고독한",
  "고요한 환희의",
  "비장히 결연한",
  "차분한",
  "관조적인",
  "무던한",
  "애틋이 따뜻한",
  "고독히 의연한",
  "담담한 향수의",
  "처연히 아름다운",
  "잔잔한 슬픔의",
  "고요한 위로의",
  "온화한 연민의",
  "초탈한",
  "담대한 고독의",
  "숭고히 비장한",
  "아련한 그리움의",
  "평온한 각성의",
  "고요한 깨달음의",
  "쓸쓸한 자유의",
  "담박한 기쁨의",
  "의연한 슬픔의",
  "고즈넉한 평화의"
];
window.WEATHERS = [
  "맑게 갠 하늘",
  "옅은 구름 낀",
  "짙은 먹구름",
  "가랑비 내리는",
  "소나기 쏟아지는",
  "장대비 퍼붓는",
  "이슬비 흩날리는",
  "안개비 자욱한",
  "함박눈 내리는",
  "싸락눈 흩날리는",
  "진눈깨비 치는",
  "서리 내린",
  "된서리 앉은",
  "엷은 안개 낀",
  "짙은 안개 낀",
  "물안개 피어오르는",
  "아침 이슬 맺힌",
  "바람 잔잔한",
  "산들바람 부는",
  "돌풍 휘몰아치는",
  "폭풍우 치는",
  "천둥 번개 치는",
  "무지개 뜬",
  "노을 붉게 물든",
  "여명이 트는",
  "땅거미 지는",
  "폭염 내리쬐는",
  "아지랑이 피는",
  "한파 몰아치는",
  "서늘한 바람의",
  "후텁지근한",
  "건조하고 청명한",
  "습하고 무거운",
  "눈보라 치는",
  "흙비 날리는",
  "황사 자욱한",
  "별이 총총한",
  "보름달 환한",
  "그믐의 캄캄한",
  "구름 사이 햇살",
  "비 갠 뒤 청명한",
  "눈 그친 고요한",
  "서리꽃 핀",
  "고드름 맺힌",
  "열대야의",
  "상쾌한 가을의",
  "포근한 봄의",
  "나른한 여름의",
  "쨍한 겨울의",
  "바람 한 점 없는",
  "미풍에 흔들리는",
  "폭설 쌓인",
  "빗방울 듣는",
  "천둥 먼 우레의",
  "번개 번뜩이는",
  "해무 자욱한",
  "아침 서리의",
  "저녁 안개의",
  "구름 한 점 없는",
  "햇무리 진",
  "달무리 진",
  "비구름 몰려오는",
  "소낙눈 흩뿌리는",
  "진주빛 흐린",
  "유리 같은 청명한",
  "납빛 흐린",
  "잿빛 안개의",
  "금빛 노을의",
  "은빛 달빛의",
  "청회색 비구름의",
  "연보랏빛 여명의",
  "주홍빛 일몰의",
  "물보라 날리는",
  "서걱이는 눈발의",
  "포근한 함박눈의",
  "칼바람 부는",
  "훈풍 부는",
  "건들바람 부는",
  "높새바람 부는",
  "마파람 부는",
  "된바람 치는",
  "꽃샘추위의",
  "늦더위의",
  "첫눈 내리는",
  "장마철 눅눅한",
  "가뭄에 메마른",
  "해빙기의 질척한",
  "서리 녹는 아침의",
  "눈 녹는 봄의",
  "우박 쏟아지는",
  "이른 봄 쌀쌀한",
  "늦가을 스산한",
  "한여름 불볕의",
  "엄동설한의",
  "비 머금은 무거운",
  "바람결 부드러운",
  "안개 걷히는",
  "구름 흩어지는",
  "햇살 부서지는",
  "빗줄기 굵은"
];
